[package]
name = "uprobe-dlp"
version = "0.1.0"
edition = "2024"

[dependencies]
aya-ebpf = "0.1.1"
ebpf-common = { path = "../../ebpf-common", default-features = false }

[[bin]]
name = "uprobe-dlp"
path = "src/main.rs"
