[package]
name = "xdp-firewall"
version = "0.1.0"
edition = "2024"

[dependencies]
aya-ebpf = "0.1.1"
ebpf-common = { path = "../../ebpf-common", default-features = false }
network-types = "0.1.0"

[[bin]]
name = "xdp-firewall"
path = "src/main.rs"
